source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'notegist' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for notegist

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'notegistTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
